[package]
name = "cracking-codes-rs"
version = "0.1.0"
authors = ["Stephen Rufle <srufle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "morse"

[dependencies]

